version: 2.1

workflows:
  version: 2
  branch:
    jobs:
      - check:
          filters:
            tags:
              ignore: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
      - rust/release-please-single:
          context: [lulubot]
          filters:
            branches:
              only:
                - main
          github_token: GITHUB_TOKEN_LULUBOT
      - build:
          context: [yuiyukihira]
          requires:
            - check
            - test
            - rust/release-please-single
          filters:
            branches:
              only:
                - main
          username: GITHUB_USERNAME
          password: GITHUB_PAT
          version: latest
  release:
    jobs:
      - check:
          filters:
            branches:
              ignore: /.*/
      - test:
          filters:
            branches:
              ignore: /.*/
      - rust/release-please-single:
          context: [lulubot]
          filters:
            branches:
              ignore: /.*/
          github_token: GITHUB_TOKEN_LULUBOT
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: [yuiyukihira]
          requires:
            - check
            - test
            - rust/release-please-single
          username: GITHUB_USERNAME
          password: GITHUB_PAT
          version: "${CIRCLE_TAG/v/''}"
jobs:
  build:
    docker:
      - image: nixos/nix:2.3.12
        environment:
          CACHIX_NAME: yuiyukihira
          VERSION: << parameters.version >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash
            cachix use $CACHIX_NAME
      - run:
          name: Build Image
          command: |
            nix-shell
            make target/romanticise-<< parameters.version >>.tar.gz
      - rust/docker-load:
          file: target/romanticise-<< parameters.version >>.tar.gz
      - rust/docker-publish:
          tag: << parameters.version >>
          image: yuiyukihira/romanticise
          registry: ghcr.io
          username: << parameters.username >>
          password: << parameters.password >>
    parameters:
      version:
        description: "Version to build"
        default: "latest"
        type: string
      username:
        description: "Docker registry username"
        type: string
      password:
        description: "Docker registry password"
        type: string
  check:
    executor: rust/rust
    steps:
      - checkout
      - run: cargo clippy --locked
  test:
    executor: rust/rust
    steps:
      - checkout
      - run: cargo test --locked

orbs:
  rust: yuiyukihira/rust@1.1.0
